### ISSUE TITLE
How do you  put binary files in the github releases?

### ISSUE THREAD

**Issue by suntong** [txthinking/nami#1]
Very interesting idea and nova approach, just that, how do you  put binary files in the github releases?

Manually doing that would be a big hurdle for people to overcome and for nami to gain popularity. thx.

**Comment by txthinking** [comment]
I have some suggestions,

1. Add config for github token, like this

$ nami config githubtoken TOKEN

2. Auto upload binaries which format is xx_OS_ARCH from a directory, like
this

$ nami publish github.com/txthinking/joker /path/to/binaries/directory/

Any idea?

**Comment by suntong** [comment]
I really like that simplicity, although since we are talking about GH releases, maybe borrowing the ready-made GitHub Actions like 

https://github.com/actions/upload-release-asset

might not be a bad idea. 

If you want to add nami official bintray distribution support apart from GH, take a look at

https://github.com/go-easygen/wireframe#binary-releases

in which building Go commands and publishing to bintray is done in CI/CD, i.e., automatically. One example is:

https://github.com/suntong/cascadia => https://bintray.com/suntong/bin/cascadia

Up to you. I believe in you that you'll come up with better solutions.

**Comment by suntong** [comment]
In my view, adding bintray distribution as nami's official support is the easiest thing to do ***first***, as building and uploading has been proven to be very easy and there are existing/working demo code. 

Getting them from bintray is super easy too. What's only remaining is the naming convention of the packages, I'd highly recommend to follow the (maybe simplified) Debian's naming convention, e.g., `package-name_ver.x.x.x_arch`, i.e., the executable would be named the same if packaged as a Debian package. 

Once the binary uploading hurdle has been over come, I can help you pack `nami` as a Debian package, so anyone using Debian or related distro like Ubuntu, can do *"open sesame" * as simple as `apt install nami`.

**Comment by suntong** [comment]
> In my view, adding bintray distribution as nami's official support is the easiest thing to do first

If you do, I'd recommend to continue the `easygen` wireframe's approach, you put a template file say `nami_bintray.json` in nami's repo, and everyone can following the exact same format that you recommend them (via `easygen nami_bintray.json ...`).

**Comment by txthinking** [comment]
> I really like that simplicity, although since we are talking about GH releases, maybe borrowing the ready-made GitHub Actions like
> 
> https://github.com/actions/upload-release-asset
> 
> might not be a bad idea.
> 
> If you want to add nami official bintray distribution support apart from GH, take a look at
> 
> https://github.com/go-easygen/wireframe#binary-releases
> 
> in which building Go commands and publishing to bintray is done in CI/CD, i.e., automatically. One example is:
> 
> https://github.com/suntong/cascadia => https://bintray.com/suntong/bin/cascadia
> 
> Up to you. I believe in you that you'll come up with better solutions.

I see, but I think nami is binary manager, not only for golang, like [joker](https://github.com/txthinking/joker), looks there is no a simple way to build and upload

**Comment by txthinking** [comment]
> In my view, adding bintray distribution as nami's official support is the easiest thing to do _**first**_, as building and uploading has been proven to be very easy and there are existing/working demo code.
> 
> Getting them from bintray is super easy too. What's only remaining is the naming convention of the packages, I'd highly recommend to follow the (maybe simplified) Debian's naming convention, e.g., `package-name_ver.x.x.x_arch`, i.e., the executable would be named the same if packaged as a Debian package.
> 
> Once the binary uploading hurdle has been overcome, I can help you pack `nami` as a Debian package, so anyone using Debian or related distro like Ubuntu, can do _"open sesame"_ as simple as `apt install nami`.

If put nami into debian, binary file format with nami is nothing about debian's format, this are two things:

apt-get install debian-package-nami
nami install nami-package-nami

**Comment by txthinking** [comment]
At present, it seems that bintray has little effect, because nami is focus on decentralized

**Comment by suntong** [comment]
> nami is focus on decentralized

Well..., I view bintray nothing different than github, as I can counter-argue that github makes every nami package centered around it. 

IMHO, decentralized means everyone can do their own releases/packages, without going through a central control, like Debian does. Thus bintray is perfectly decentralized, just like github is.

**Comment by txthinking** [comment]
Yes, you are right.

With v20200513, can use `nami release github.com/x/x v1.1.1 ./dir/` to publish/update a version.

As [wiki](https://github.com/txthinking/nami/wiki) described, nami supports making packages on your own server.

On github, we can:

1. nami can know the package name, such github.com/x/x (package name has domain, nami can execute other commands based on this)
2. nami can get latest version via github api
3. nami can download binary file via github api
4. nami can release version and binaries via github api or create release by self

On own server, we can:

1. nami can know the package name, such own.server.com/x/x (package name has domain, nami can execute other commands based on this)
2. nami can get latest version via https://own.server.com/x/x/nami.json
3. nami can download binary file via https://own.server.com/x/x/nami.json
4. create release by self

Can you describe your complete idea and combine above description? thx

**Comment by suntong** [comment]
> Can you describe your complete idea and combine above description

As I've put it, uploading to and getting them from bintray are super easy. *"What's only remaining is the naming convention of the packages"*, however, 

> I'd recommend to continue the easygen wireframe's approach, you put a template file say nami_bintray.json in nami's repo, and everyone can following the exact same format that you recommend them (via easygen nami_bintray.json ...).

I.e., the naming convention of the packages can be / is defined in the template. Then the same as  `nami install github.com/suntong/cascadia`, getting from bintray would be as simple as `nami install bintray.com/suntong/bin/cascadia` without the need for the user to use `nami.json`, as long as everyone is following the same naming convention you defined in the template. 

That's the whole idea. If we can agree on that, then the rest are simple.

**Comment by txthinking** [comment]
Sorry, I don't understand that how the template(nami_binary.json) interacts with user and publisher, like

- When user nami install package, nami how to know the latest version number?
- Publisher or package author how and why to use it? 

I always like simple, zero configuration, one command to solve things, less concepts and keep transparent. People don't like to read 'more document', love at first sight.

If we can `nami install bintray.com/xx/xx`, then

- When user nami install package, nami how to know the latest version number?
- When user nami install package, nami how to know the all binary files under this package?

And an important thing, because installed is `binary` not source, that means package should have a decent website for the package.

**Comment by suntong** [comment]
For all the above question, the answer should be the same as how github releasing is handled. I don't think there should be any differences, maybe because I don't know the inside details... 

FTR, Debian's naming convention has a very detailed rules on how to tell which version is newer, more than necessary for nami's case.

**Comment by txthinking** [comment]
> For all the above question, the answer should be the same as how github releasing is handled. I don't think there should be any differences, maybe because I don't know the inside details...

Yes

> 
> FTR, Debian's naming convention has a very detailed rules on how to tell which version is newer, more than necessary for nami's case.

Yes

But executable detailed proposal is better. Any detail and feel free to open again.
