### ISSUE TITLE
建议优化安装脚本

### ISSUE THREAD

**Issue by NowAnti** [txthinking/nami#11]
机器位于国内，安装nami遇到点儿麻烦：

- nami似乎不支持socks5代理？给系统设置了了all_proxy=socks5://，下载可以用了，但是nami还是提示连不到
- 安装脚本里面似乎是先下载了个nami到tmp，再用nami安装nami，这个过程又下载了一遍安装包150+mb。。。

**Comment by NowAnti** [comment]
安装包体积可以优化下吗 略庞大了还有个是 编译必须用GLIBC_2.18吗？最近在谷歌云和本地机器新装的2个CentOS上都没有这么库，只能现编译，谷歌的机器配置开的低，编译了几个小时。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [txthinking/nami] 建议优化安装脚本 (Issue #11)





  
机器位于国内，安装nami遇到点儿麻烦：
  
这个没有什么好办法，好像没有口碑好点的地方可以放包文件
   
nami似乎不支持socks5代理？给系统设置了了all_proxy=socks5://，下载可以用了，但是nami还是提示连不到
   
all_proxy好像是没有https_proxy通用，基本用的就是go, deno(rust)原始网络库，https_proxy=127.0.0.1:8010 nami install ...
   
安装脚本里面似乎是先下载了个nami到tmp，再用nami安装nami，这个过程又下载了一遍安装包150+mb。。。
   
嗯，这块有待优化一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by txthinking** [comment]
现在是nami用内嵌的deno执行安装脚本比较方便，deno是rust写的，rust依赖GLIBC_2.18
centos不都不维护了吗，这个系统里的包都太老了

**Comment by NowAnti** [comment]
懂了。不过centos7 还有几年维护周期 而且实际应用跟官方停止维护还是会有几年时间差的 用户暂时不会少多少的

**Comment by txthinking** [comment]
已优化为一次
