### ISSUE TITLE
Why use deno?

### ISSUE THREAD

**Issue by FirYuen** [txthinking/nami#16]
你好, 去年曾经关注过这个项目,之前使用时是nami加上远程文件夹中的json配置文件,想请教为什么现在要改用内置一个deno,同时需要编写deno的js脚本去进行下载操作呢?内嵌deno不仅导致nami的可执行文件体积暴增,deno的js编写也没有似乎也简化创建软件包的过程

**Comment by FirYuen** [comment]
其实关于包维护的问题我可以理解,但是我的疑问是:
既然选择了使用go那么是否本身就应该使用go 去进行 配置文件的解析,可执行文件的下载,解压释放等操作,而不是在go中嵌入一个deno,然后用deno去解析js文件并进行下载,解压等操作.

从另一个角度来说,那些js中已经写出了文件的完整下载路径,某种意义上来将此时我甚至不需要deno,只需要写一个简单的shell脚本就能做到下载,安装等操作

整体目前的nami给我的感觉是"诡异",我更加喜欢以前的nami,直接去访问远程的json读取配置进行解析下载.nami本身也非常轻量,只有不到10M,而不是像现在体积快到100M...

**Comment by FirYuen** [comment]
我理解到了您的想法了.
我之前的使用场景是自己维护了一个对象存储,将自己编译出的可执行文件上传到了服务器当中,所以nami十分好用. 但是这是类似debian的配置文件的做法,由维护者去维护线上的软件版本.
您目前的做法是采用brew的做法,使用了一个runtime去执行脚本,因为要解决软件作者可能没有按照格式进行发布的问题.

我还是很怀念之前的nami,功能好用,十分十分符合我当时的需求,并且我没有找到类似的软件.
但是现在的模式我好像找到了几个类似的,专门从github release去下载安装的包管理器,比如: [stew](https://github.com/marwanhawari/stew),[indiepkg](https://github.com/talwat/indiepkg),[afk](https://github.com/b4b4r07/afx)

再说一句..其实目前nami比较让我觉得难受的还是可执行的文件的大小,deno实在太大了,在部分家庭网络环境中从github release下载会遇到劫持等问题,并且下载速度会十分不理想.

ps: 最近看到您添加了tengo,请问后续有计划转为使用tengo的runtime吗?

**Comment by txthinking** [comment]
#### 维护自己的包的方式，核心就是脚本把命令文件放到 `$HOME/.nami/cache/` 目录下即可

比如：

`cat brook.tengo`
```
name := "brook" // the package name you are installing, or dynamic get from URL path with your custom server

config := {
  "brook_linux_amd64": "https://github.com/txthinking/brook/releases/latest/download/brook_linux_amd64",
  "brook_darwin_amd64": "https://github.com/txthinking/brook/releases/latest/download/brook_darwin_amd64",
  "brook_darwin_arm64": "https://github.com/txthinking/brook/releases/latest/download/brook_darwin_arm64",
  "brook_windows_amd64.exe": "https://github.com/txthinking/brook/releases/latest/download/brook_windows_amd64.exe"
}

/////下面的基本不需要改，非基本可以自己稍微改改，核心就是脚本把命令文件放到HOME/.nami/cache/目录下///

os := import("os")
fmt := import("fmt")
text := import("text")
nami := import("nami")

nami.sh("curl", "-L", "--progress-bar", config[name + "_" + nami.os + "_" + nami.arch + (nami.os == "windows" ? ".exe" : "")], "-o", text.join([nami.cache_dir, name + (nami.os == "windows" ? ".exe" : "")], os.path_separator))
```
可以放到本地
```
nami install ./brook.tengo
```
可以讲这个`brook.tengo`放到自己的http server,就可以
```
nami install https://yourserver.com/brook.tengo
```

#### 也可以动态的输出脚本, 比如借助 https://deno.com/deploy 省了自己的服务器

```
import httpserver from 'https://raw.githubusercontent.com/txthinking/denolib/master/httpserver.js';

function get_tengo_script(name){
  return `
name := "${name}" // the package name you are installing, or dynamic get from URL path with your custom server

config := {
  "brook_linux_amd64": "https://github.com/txthinking/brook/releases/latest/download/brook_linux_amd64",
  "brook_darwin_amd64": "https://github.com/txthinking/brook/releases/latest/download/brook_darwin_amd64",
  "brook_darwin_arm64": "https://github.com/txthinking/brook/releases/latest/download/brook_darwin_arm64",
  "brook_windows_amd64.exe": "https://github.com/txthinking/brook/releases/latest/download/brook_windows_amd64.exe",
  "httpserver_linux_amd64": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_linux_amd64",
  "httpserver_darwin_amd64": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_darwin_amd64",
  "httpserver_darwin_arm64": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_darwin_arm64",
  "httpserver_windows_amd64.exe": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_windows_amd64.exe"
}

////下面的基本不需要改，非基本可以自己稍微改改，核心就是脚本把命令文件放到HOME/.nami/cache/目录下//////

os := import("os")
fmt := import("fmt")
text := import("text")
nami := import("nami")

nami.sh("curl", "-L", "--progress-bar", config[name + "_" + nami.os + "_" + nami.arch + (nami.os == "windows" ? ".exe" : "")], "-o", text.join([nami.cache_dir, name + (nami.os == "windows" ? ".exe" : "")], os.path_separator))
`;
}

httpserver.path('/brook.tengo', async (r)=>new Response(get_tengo_script("brook")))
httpserver.path('/httpserver.tengo', async (r)=>new Response(get_tengo_script("httpserver")))

httpserver.run({port:8080});
```

就可以这样
```
nami install https://XXX.deno.dev/brook.tengo
nami install https://XXX.deno.dev/httpserver.tengo
```

**Comment by FirYuen** [comment]
> import httpserver from 'https://raw.githubusercontent.com/txthinking/denolib/master/httpserver.js';
> 
> function get_tengo_script(name){
>   return `
> name := "${name}" // the package name you are installing, or dynamic get from URL path with your custom server
> 
> config := {
>   "brook_linux_amd64": "https://github.com/txthinking/brook/releases/latest/download/brook_linux_amd64",
>   "brook_darwin_amd64": "https://github.com/txthinking/brook/releases/latest/download/brook_darwin_amd64",
>   "brook_darwin_arm64": "https://github.com/txthinking/brook/releases/latest/download/brook_darwin_arm64",
>   "brook_windows_amd64.exe": "https://github.com/txthinking/brook/releases/latest/download/brook_windows_amd64.exe",
>   "httpserver_linux_amd64": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_linux_amd64",
>   "httpserver_darwin_amd64": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_darwin_amd64",
>   "httpserver_darwin_arm64": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_darwin_arm64",
>   "httpserver_windows_amd64.exe": "https://github.com/txthinking/httpserver/releases/latest/download/httpserver_windows_amd64.exe"
> }
> 
> ////下面的基本不需要改，非基本可以自己稍微改改，核心就是脚本把命令文件放到HOME/.nami/cache/目录下//////
> 
> os := import("os")
> fmt := import("fmt")
> text := import("text")
> nami := import("nami")
> 
> nami.sh("curl", "-L", "--progress-bar", config[name + "_" + nami.os + "_" + nami.arch + (nami.os == "windows" ? ".exe" : "")], "-o", text.join([nami.cache_dir, name + (nami.os == "windows" ? ".exe" : "")], os.path_separator))
> `;
> }
> 
> httpserver.path('/brook.tengo', async (r)=>new Response(get_tengo_script("brook")))
> httpserver.path('/httpserver.tengo', async (r)=>new Response(get_tengo_script("httpserver")))
> 
> httpserver.run({port:8080});

十分感谢! 经过测试完全可以满足我需求了!

**Comment by m2acgi** [comment]
建议采用这种方式 https://github.com/izirku/gitrel， 不需要包作者适配任何东西，也不要 nami仓库维护者，直接从 github 安装任何二进行文件，但是这个项目停止更新的，最后一个 release 也不兼容最新的主流 linux 发行版。
