### ISSUE TITLE
nami在Windows下如何安装使用？

### ISSUE THREAD

**Issue by suntong** [txthinking/nami#2]
如题
How to use nami in Windows. thx.

**Comment by txthinking** [comment]
The problem is how to run one command to get a script and execute it and
update PATH

**Comment by suntong** [comment]
> All files are stored in ~/.nami

So where would all downloaded files are stored in Windows then?

**Comment by suntong** [comment]
> The problem is how to run one command to get a script

If this is a question meant for me, then you can assume that people would have git-bash under Windows, which 99.9% of programmer are having nowadays. 

This means that `bash`, `git` and `curl` are ready at their fingertips. 

> update PATH

That'll be a piece of cake, `setx`.

**Comment by txthinking** [comment]
https://stackoverflow.com/questions/9228950/what-is-the-alternative-for-users-home-directory-on-windows-command-prompt

**Comment by txthinking** [comment]
fixed
