### ISSUE TITLE
Installation Failure: curl Package via nami on Debian 6.1

### ISSUE THREAD

**Issue by Mike-Acb** [txthinking/nami#29]
## Environment
- **Operating System:** Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
- **Nami Version:** 20240408

## Issue Description
I encountered an error while trying to install the `curl` package using `nami`. The installation process fails during the extraction and setup steps, leading to an incomplete installation.

## Steps to Reproduce
1. Run `nami install curl` on the terminal.
2. Observe the error output.

## Expected Behavior
The `curl` package should be installed successfully without any errors.

## Actual Behavior
The installation process fails with the following error messages:

```shell
root@jp:/tmp/_# nami install curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 87661    0 87661    0     0   243k      0 --:--:-- --:--:-- --:--:--  244k
######################################################################## 100.0%
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat '/tmp/_/curl': No such file or directory
+-------------------+-------+
| Package           | curl  |
|                   |       |
| Installed Version | 8.8.0 |
| Installed Files   |       |
+-------------------+-------+
root@jp:/tmp/_# nami --version
nami version 20240408
root@jp:/tmp/_# uname -a
Linux jp 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
```

**Comment by txthinking** [comment]
fix https://github.com/txthinking/nami/commit/e7ff1af93a68e5d17c8ded6046e7eee275d7aa56
