### ISSUE TITLE
Private github token readable by anyone on the system

### ISSUE THREAD

**Issue by stefanb** [txthinking/nami#31]
Configured private Github token is stored unencrypted in `~/.nami/db` file, with permissions `rw-r--r--`, allowing anybody on the system reading that file.

Workaround: manually set permission of that file to be readable ony by the user (`rw-------`) via:
````bash
$ chmod go-rwx ~/.nami/db
````

A proper fix would be to create proper file permission when writing the `db` file (or even adjust them on existing config whenever `nami` is executed).

**Comment by txthinking** [comment]
You are meticulous, and I have also invited you to join nami.

**Comment by stefanb** [comment]
Tnx, merged fix from #32 and another security update #33 and then released [v20240901](https://github.com/txthinking/nami/releases/tag/v20240901).

**Comment by txthinking** [comment]
There is a hardcode(this maybe not a good idea 😬) version number in the main.go to check if an upgrade is needed, so I released v20240902 fixed this.

**Comment by stefanb** [comment]
Thank you, I missed that.
