### ISSUE TITLE
unable to install in Termux.

### ISSUE THREAD

**Issue by 5c0tt1** [txthinking/nami#5]
Thank you! this works great on my PC, I tried adding it to Termux for when im out on the go, but I got an error:
```
2021/01/22 13:37:33 Get "https://api.github.com/repos/txthinking/nami/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:38965->[::1]:53: read: connection refused
```
Thank you once again!

**Comment by txthinking** [comment]
nami support linux amd64, macos, windows amd64 :)
